namespace = "https://example.com/"

[shapes.Recipe]
[shapes.Recipe.name]
name = "string"
[shapes.Recipe.author]
author = "string"
[shapes.Recipe.source]
kind = "reference"
label = "Webpage"
cardinality = "required"
[shapes.Recipe.ingredient]
kind = "reference"
label = "Ingredient"
cardinality = "any"

[shapes.Ingredient]
name = "string"
[shapes.Ingredient.id]
kind = "uri"
[shapes.Ingredient.description]
kind = "literal"
datatype = "string"
cardinality = "optional"

[classes.Webpage]
[classes.Webpage.url]
kind = "literal"
datatype = "string"
cardinality = "required"
[classes.Webpage.author]
kind = "literal"
datatype = "string"
cardinality = "any"