namespace = "https://example.com/"

[classes.Graph]
[classes.Graph.name]
kind="literal"
datatype = "string"
cardinality = "optional"
[classes.Graph.wasGeneratedBy]
kind = "reference"
label = "Scraper"
cardinality = "optional"

[classes.Scraper]
url = "string"
[classes.Scraper.author]
kind = "literal"
datatype = "string"
cardinality = "optional"