namespace = "https://example.com/"

[classes.Graph]
[classes.Graph.wasDerivedFrom]
kind = "reference"
label = "Webpage"

[classes.Webpage]
url = "string"
[classes.Webpage.author]
kind = "literal"
datatype = "string"
cardinality = "optional"